n = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(n))
print('é espaço?', n.isspace())
print('é numero', n.isnumeric())
print('é alfabético', n.isalpha())
print('é alfanumérico', n.isalnum())
print("está em maiuscula", n.isupper())
print('está em minuscula', n.islower())
print('Esta capitalizada', n.istitle())
